-- insertion données dans la table catégorie
INSERT INTO categorie(nom) VALUES
("mont"),
("equerre"),
("plaque"),
("poulie"),
("vis"),
("roue"),
("ressort"),
("sup"),
("trg"),
("rcd"),
("crochet"),
("corniere"),
("cheville"),
("cavalier"),
("boulon"),
("bnd"),
("anneau"),
("bague"),
("rondelle"),
("clavette"),
("disque"),
("ecrou"),
("pignon"),
("pleu");

-- insertion des données dans la table produit
INSERT INTO produit (nom, description, prix, image, id_categorie) VALUES
("montBC6", "montBC6", 14.99, "./src/images/produits/montBC6.jpg", 1),
("montBC13", "montBC13", 9.99, "./src/images/produits/montBC13.jpg", 1),
("anneauCaoutchout", "anneauCaoutchout", 9.99, "./src/images/produits/anneauCaoutchout.jpg", 17),
("bague", "bague", 19.99, "./src/images/produits/bague.jpg", 18),
("bndCoudee", "bndCoudee", 29.99, "./src/images/produits/bndCoudee.jpg", 16),
("boulonPivot", "boulonPivot", 12.99, "./src/images/produits/boulonPivot.jpg", 15),
("cavalier", "cavalier", 39.99, "./src/images/produits/cavalier.jpg", 14),
("chevilleFilete", "chevilleFilete", 59.99, "./src/images/produits/chevilleFilete.jpg", 13),
("corniere", "corniere", 3.99, "./src/images/produits/corniere.jpg", 12),
("crochet", "crochet", 149.99, "./src/images/produits/crochet.jpg", 11),
("equerre135", "equerre135", 9.99, "./src/images/produits/equerre135.jpg", 2),
("longrine", "longrine", 9.99, "./src/images/produits/longrine.jpg", 1),
("montBC1", "montBC1", 19.99, "./src/images/produits/montBC1.jpg", 1),
("montBC2", "montBC2", 49.99, "./src/images/produits/montBC2.jpg", 1),
("montBC3", "montBC3", 29.99, "./src/images/produits/montBC3.jpg", 1),
("montBC4", "montBC4", 19.99, "./src/images/produits/montBC4.jpg", 1),
("montBC5", "montBC5", 56.99, "./src/images/produits/montBC5.jpg", 1),
("montBC7", "montBC7", 5.99, "./src/images/produits/montBC7.jpg", 1),
("montBC10", "montBC10", 99.99, "./src/images/produits/montBC10.jpg", 1),
("montBC11", "montBC11", 1.99, "./src/images/produits/montBC11.jpg", 1),
("montBC12", "montBC12", 3.99, "./src/images/produits/montBC12.jpg", 1),
("montBC14", "montBC14", 7.99, "./src/images/produits/montBC14.jpg", 1),
("plaque", "plaque", 13.99, "./src/images/produits/plaque.jpg", 3),
("plqCintree", "plqCintree", 4.99, "./src/images/produits/plqCintree.jpg", 3),
("plqCintreU", "plqCintreU", 7.99, "./src/images/produits/plqCintreU.jpg", 3),
("plqPlstiqClair", "plqPlstiqClair", 14.99, "./src/images/produits/plqPlstiqClair.jpg", 3),
("plqSecteur", "plqSecteur", 3.99, "./src/images/produits/plqSecteur.jpg", 3),
("pneu4Poulie", "pneu4Poulie", 8.99, "./src/images/produits/pneu4Poulie.jpg", 1),
("poulie2Moyeu", "poulie2Moyeu", 27.99, "./src/images/produits/poulie2Moyeu.jpg", 4),
("ressortAttache", "ressortAttache", 24.99, "./src/images/produits/ressortAttache.jpg", 7),
("rondelle", "rondelle", 12.99, "./src/images/produits/rondelle.jpg", 19),
("supDouble", "supDouble", 9.99, "./src/images/produits/supDouble.jpg", 8),
("vis", "vis", 89.99, "./src/images/produits/vis.jpg", 5),
("visLong", "visLong", 29.99, "./src/images/produits/visLong.jpg", 5),
("bndCintreGlisier", "bndCintreGlisier", 19.99, "./src/images/produits/bndCintreGlisier.jpg", 16),
("bndCurve", "bndCurve", 23.99, "./src/images/produits/bndCurve.jpg", 16),
("clavette", "clavette", 41.99, "./src/images/produits/clavette.jpg", 20),
("disque", "disque", 12.99, "./src/images/produits/disque.jpg", 21),
("ecrou", "ecrou", 2.99, "./src/images/produits/ecrou.jpg", 22),
("equerre90", "equerre90", 59.99, "./src/images/produits/equerre90.jpg", 2),
("montBC8", "montBC8", 49.99, "./src/images/produits/montBC8.jpg", 1),
("pignon", "pignon", 39.99, "./src/images/produits/pignon.jpg", 23),
("pleuAuto", "pleuAuto", 29.99, "./src/images/produits/pleuAuto.jpg", 24),
("plqBande", "plqBande", 19.99, "./src/images/produits/plqBande.jpg", 3),
("plqDemiCirc", "plqDemiCirc", 9.99, "./src/images/produits/plqDemiCirc.jpg", 3),
("plqFlexible", "plqFlexible", 99.99, "./src/images/produits/plqFlexible.jpg", 3),
("plqFlexTrg", "plqFlexTrg", 34.99, "./src/images/produits/plqFlexTrg.jpg", 3),
("plqPlstiqBleu", "plqPlstiqBleu", 32.99, "./src/images/produits/plqPlstiqBleu.jpg", 3),
("plqRebord", "plqRebord", 23.99, "./src/images/produits/plqRebord.jpg", 3),
("poulie", "poulie", 12.99, "./src/images/produits/poulie.jpg", 4),
("poulie2", "poulie2", 23.99, "./src/images/produits/poulie2.jpg", 4),
("poulieMoyeu", "poulieMoyeu", 21.99, "./src/images/produits/poulieMoyeu.jpg", 4),
("rcdTringlBnd", "rcdTringlBnd", 54.99, "./src/images/produits/rcdTringlBnd.jpg", 10),
("rcdTringlBnd90", "rcdTringlBnd90", 23.99, "./src/images/produits/rcdTringlBnd90.jpg", 10),
("rcdTringle", "rcdTringle", 12.99, "./src/images/produits/rcdTringle.jpg", 10),
("roueBarillet", "roueBarillet", 189.99, "./src/images/produits/roueBarillet.jpg", 6),
("roueDentee", "roueDentee", 12.99, "./src/images/produits/roueDentee.jpg", 6),
("tigeFilete", "tigeFilete", 3.99, "./src/images/produits/tigeFilete.jpg", 9),
("trgEmbase", "trgEmbase", 5.99, "./src/images/produits/trgEmbase.jpg", 9),
("trgEmbaseCoude", "trgEmbaseCoude", 2.99, "./src/images/produits/trgEmbaseCoude.jpg", 9),
("tringle", "tringle", 9.99, "./src/images/produits/tringle.jpg", 9),
("equerreRenv", "equerreRenv", 19.99, "./src/images/produits/equerreRenv.jpg", 2),
("supPlat", "supPlat", 29.99, "./src/images/produits/supPlat.jpg", 8);

-- insertion des données dans la table conseil
INSERT INTO conseil (nom, description, image) VALUES
("montage1", "montage1", "./src/images/montages/montage1.png"),
("montage2", "montage2", "./src/images/montages/montage2.jpg");

-- insertion des données dans la table conseil_produit
INSERT INTO conseil_produit(id_conseil, id_produit, quantite) VALUES
(1, 1, 1),
(1, 2, 1),
(1, 13, 1),
(1, 14, 1),
(1, 15, 1),
(1, 16, 1),
(1, 17, 1),
(1, 18, 1),
(1, 19, 1),
(1, 20, 1),
(1, 21, 1),
(1, 22, 1),
(1, 41, 1),
(2, 46, 3),
(2, 23, 1),
(2, 34, 4);

-- insertion des données dans la table promotion
INSERT INTO promotion(date_fin, rabais, id_produit) VALUES
('2022-12-29', 25, 23),
('2022-12-23', 30, 54),
('2023-01-02', 50, 12);